# ============================================================
# Zelda: Shattered Realms — Makefile using libdragon n64.mk
# Auto-includes all C files in src/, builds bootable .z64 via libdragon macro
# ============================================================

N64_INST ?= /opt/libdragon

# ---------- Project metadata ----------
TARGET          := shattered_realms
N64_ROM_TITLE   := Shattered Realms
N64_ROM_REGION  := E
N64_ROM_MEDIA   := N
N64_ROM_SIZE    := 2M

# ---------- Sources (auto-discover every .c under src/)
SOURCES := $(wildcard src/*.c)

# ---------- Assets / ROMFS ----------
ROMFS_DIRS := assets/romfs

# --- Locate libdragon's n64.mk (try multiple common locations) ---
N64_MK := $(firstword \
  $(wildcard $(N64_INST)/n64.mk) \
  $(wildcard $(N64_INST)/libdragon/n64.mk) \
  $(wildcard $(N64_INST)/mips64-elf/libdragon/n64.mk) \
)
ifeq ($(strip $(N64_MK)),)
$(error Could not find libdragon n64.mk. Looked in: \
  $(N64_INST)/n64.mk, \
  $(N64_INST)/libdragon/n64.mk, \
  $(N64_INST)/mips64-elf/libdragon/n64.mk. \
  Ensure your workflow copies /tmp/libdragon/n64.mk to $(N64_INST)/n64.mk)
endif

include $(N64_MK)

# Build targets generated by libdragon:
#   build/$(TARGET).elf, build/$(TARGET).z64, build/$(TARGET).dfs (if ROMFS present)
$(call N64_BUILD_ROM,$(TARGET))

# ---------- Default goal & helper rules ----------
.PHONY: default all copyouts showpaths clean distclean precheck
.DEFAULT_GOAL := default
all: default

# Quick sanity: make sure main.c exists and contains "int main"
precheck:
	@set -e; \
	test -f src/main.c || { echo "ERROR: src/main.c missing"; exit 1; }; \
	grep -q "int main" src/main.c || { echo "ERROR: main() not found in src/main.c"; exit 1; }; \
	echo "OK: src/main.c with main() present."

# Build the ROM, copy outputs to repo root, and print header/size
default: precheck build/$(TARGET).z64 copyouts
	@echo "ROM header (first 16 bytes):"
	xxd -l 16 -g 1 $(TARGET).z64 || true
	@echo "ROM size (bytes):"
	@wc -c < $(TARGET).z64 || true

copyouts:
	cp -f build/$(TARGET).z64 $(TARGET).z64
	cp -f build/$(TARGET).elf $(TARGET).elf
	@if [ -f build/$(TARGET).dfs ]; then cp -f build/$(TARGET).dfs romfs.dfs; fi

showpaths:
	@echo "Using N64_INST     = $(N64_INST)"
	@echo "n64.mk             = $(N64_MK)"
	@echo "N64_TOOLCHAIN_ROOT = $(N64_TOOLCHAIN_ROOT)"
	@echo "N64_TRIPLET        = $(N64_TRIPLET)"
	@echo "N64_CC             = $(N64_CC)"
	@echo "N64_LD_SCRIPT      = $(N64_LD_SCRIPT)"

clean:
	@$(RM) -rf build

distclean: clean
	@$(RM) -f $(TARGET).z64 $(TARGET).elf romfs.dfs
