name: Build Shattered Realms ROM (prebuilt toolchain from release)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOOLCHAIN_ROOT: /home/runner/.local/toolchain
      N64_INST: /home/runner/.local/libdragon

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex tree

      - name: Download prebuilt toolchain from release
        run: |
          mkdir -p "$TOOLCHAIN_ROOT"
          cd "$TOOLCHAIN_ROOT"
          echo "Fetching prebuilt toolchain from release..."
          wget -q https://github.com/user-attachments/files/22749603/gcc-toolchain-mips64-latest.tar.gz
          tar -xzf gcc-toolchain-mips64-latest.tar.gz
          echo "Extracted toolchain directory layout:"
          tree -L 4 "$TOOLCHAIN_ROOT" || find "$TOOLCHAIN_ROOT" -maxdepth 4 -type d

      - name: Detect compiler path
        id: detect
        run: |
          COMP_PATH=$(find /home/runner/.local/toolchain -type f -name "mips64-elf-gcc" -printf '%h\n' | head -n1)
          echo "Detected compiler path: $COMP_PATH"
          echo "COMP_PATH=$COMP_PATH" >> $GITHUB_ENV
          if [ -z "$COMP_PATH" ]; then
            echo "No compiler found — check archive contents above."
            exit 1
          fi

      - name: Prepare libdragon environment
        run: |
          export PATH="$COMP_PATH:$PATH"
          export N64_INST=/home/runner/.local/libdragon

          if [ -f /home/runner/.local/libdragon/include/n64.h ]; then
            echo "Prebuilt libdragon detected; skipping install."
          else
            echo "Installing fresh libdragon..."
            rm -rf /home/runner/.local/libdragon
            git clone --depth=1 https://github.com/DragonMinded/libdragon.git /home/runner/.local/libdragon
            cd /home/runner/.local/libdragon
            which mips64-elf-gcc || (echo "Compiler still missing!" && exit 1)
            make install
          fi

      - name: Verify compiler
        run: |
          echo "PATH=$PATH"
          command -v mips64-elf-gcc || (echo "Compiler still not found!" && exit 1)

      - name: Build ROM
        shell: bash
        run: |
          set -e
          echo "Building Shattered Realms ROM..."
          cd $GITHUB_WORKSPACE
          export PATH="$COMP_PATH:$PATH"
          export N64_INST=/home/runner/.local/libdragon
          which mips64-elf-gcc
          ls -R | head -50
          make clean all 2>&1 | tee build.log
          echo "Build complete."

      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
