name: Build Shattered Realms ROM (official toolchain .deb)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # The .deb installs here and sets up headers/libs/tools
      N64_INST: /opt/libdragon

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex dpkg

      # Install the official prebuilt toolchain (.deb)
      # Note: this URL/filename comes from the libdragon wiki "Option 2" instructions
      - name: Install libdragon toolchain (.deb)
        run: |
          set -e
          cd /tmp
          echo "Fetching official libdragon toolchain (.deb)..."
          wget -q https://github.com/DragonMinded/libdragon/releases/download/toolchain-continuous-prerelease/gcc-toolchain-mips64-x86_64.deb
          sudo dpkg -i gcc-toolchain-mips64-x86_64.deb
          # dpkg installs toolchain under /opt/libdragon and sets env via profile.d on real machines.
          # In CI we export the env directly:
          echo "N64_INST=/opt/libdragon" >> "$GITHUB_ENV"
          echo "/opt/libdragon/bin" >> "$GITHUB_PATH"

      - name: Build & install libdragon (headers/libs/tools)
        run: |
          set -e
          export N64_INST=/opt/libdragon
          export PATH=/opt/libdragon/bin:$PATH
          if [ -f "/opt/libdragon/include/n64.h" ]; then
            echo "libdragon already installed; skipping build.sh"
          else
            echo "Cloning and installing libdragon..."
            git clone --depth=1 https://github.com/DragonMinded/libdragon.git /tmp/libdragon-src
            cd /tmp/libdragon-src
            which mips64-elf-gcc
            ./build.sh   # this installs libdragon to $N64_INST
          fi

      - name: Verify compiler & tools
        run: |
          set -e
          export PATH=/opt/libdragon/bin:$PATH
          command -v mips64-elf-gcc
          mips64-elf-gcc --version | head -1
          command -v n64tool
          command -v mkdfs

      - name: Build ROM
        shell: bash
        run: |
          set -e
          export N64_INST=/opt/libdragon
          export PATH=/opt/libdragon/bin:$PATH
          echo "Repo listing (first 50 lines):"
          ls -R | head -50
          make clean all 2>&1 | tee build.log
          echo "Build complete."

      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
