name: Build ROM (official toolchain + SDK)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      N64_INST: /opt/libdragon
      # Keep a sane PATH; we'll append $N64_INST/bin for the build step
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential curl git jq

      - name: Install libdragon toolchain (.deb from latest toolchain release, arch-aware)
        run: |
          set -e
          ARCH=$(dpkg --print-architecture)  # e.g., amd64, arm64
          echo "Runner architecture: $ARCH"

          API="https://api.github.com/repos/DragonMinded/libdragon/releases/tags/toolchain-continuous-prerelease"
          ASSETS_JSON=$(curl -fsSL "$API")

          # Map dpkg arch -> asset pattern
          case "$ARCH" in
            amd64)  PATTERN='(x86_64|amd64)\.deb$' ;;
            arm64)  PATTERN='(aarch64|arm64)\.deb$' ;;
            *)      echo "Unsupported arch: $ARCH"; echo "$ASSETS_JSON" | jq -r '.assets[].name'; exit 1 ;;
          esac

          DEB_URL=$(echo "$ASSETS_JSON" | jq -r --arg re "$PATTERN" \
                    '.assets[] | select(.name | test($re)) | .browser_download_url' | head -n1)

          if [ -z "$DEB_URL" ]; then
            echo "Could not find a toolchain .deb matching pattern $PATTERN for arch=$ARCH" >&2
            echo "Available assets:"
            echo "$ASSETS_JSON" | jq -r '.assets[].name'
            exit 1
          fi

          echo "Downloading toolchain: $DEB_URL"
          curl -fsSL "$DEB_URL" -o /tmp/n64-toolchain.deb
          sudo dpkg -i /tmp/n64-toolchain.deb

          echo "N64_INST is set to: ${N64_INST}"

      - name: Install libdragon SDK (headers, libs, tools)
        run: |
          set -e
          git clone --depth=1 https://github.com/DragonMinded/libdragon.git /tmp/libdragon
          cd /tmp/libdragon
          # Installs headers, libraries, tools (n64tool, mkdfs, chksum64) into $N64_INST
          ./build.sh

      - name: Diagnose toolchain & SDK
        run: |
          set -e
          echo "Probing tools and files..."
          command -v mips64-elf-gcc || true
          command -v n64tool || true
          command -v mkdfs || true
          command -v chksum64 || true
          ls -l $N64_INST/mips64-elf/include/libdragon.h || true
          ls -l $N64_INST/mips64-elf/lib/n64.ld || true
          echo "PATH=$PATH"
          echo "N64_INST=$N64_INST"

      - name: Build ROM
        env:
          PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$N64_INST/bin
        run: |
          set -e
          echo "--- Makefile paths ---"
          make showpaths
          echo "----------------------"
          make clean all 2>&1 | tee build.log
          echo "✅ Build complete."
          ls -l shattered_realms.* romfs.dfs || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
            build.log
          if-no-files-found: error
