name: Build ROM (Libdragon source build fixed)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar build-essential git python3 unzip texinfo bison flex

      - name: Download toolchain source
        run: |
          wget https://github.com/n64-tools/gcc-toolchain-mips64/archive/refs/tags/latest.tar.gz
          tar -xzf latest.tar.gz
          mv gcc-toolchain-mips64-* mips64-elf-toolchain
          echo "$(pwd)/mips64-elf-toolchain/bin" >> $GITHUB_PATH

      - name: Build and install libdragon
        run: |
          git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
          cd /opt/libdragon
          export PATH="$(pwd)/../../mips64-elf-toolchain/bin:$PATH"
          make install
        shell: bash

      - name: Build ROM
        run: |
          export PATH="$(pwd)/mips64-elf-toolchain/bin:$PATH"
          make clean all
        shell: bash

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs
