name: Build Shattered Realms ROM (prebuilt toolchain)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # Keep toolchain separate from libdragon to avoid accidental deletion
      TOOLCHAIN_ROOT: /home/runner/.local/toolchain
      TOOLCHAIN_BIN:  /home/runner/.local/toolchain/bin
      N64_INST:       /home/runner/.local/libdragon

    steps:
      # 1) Checkout repo
      - uses: actions/checkout@v4

      # 2) Base deps
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      # 3) Download the OFFICIAL prebuilt toolchain (has mips64-elf-gcc binaries)
      - name: Download prebuilt toolchain from libdragon release
        run: |
          set -e
          mkdir -p "$TOOLCHAIN_ROOT"
          cd "$TOOLCHAIN_ROOT"
          echo "Fetching official prebuilt toolchain..."
          wget -q https://github.com/DragonMinded/libdragon/releases/download/toolchain-latest/mips64-elf-toolchain-linux.tar.gz
          tar -xzf mips64-elf-toolchain-linux.tar.gz
          # Export PATH for later steps
          echo "$TOOLCHAIN_BIN" >> "$GITHUB_PATH"

      # 4) Prepare libdragon include/lib (skip install if already present)
      - name: Prepare libdragon environment
        run: |
          set -e
          export PATH="$TOOLCHAIN_BIN:$PATH"
          export N64_INST="$N64_INST"

          if [ -f "$N64_INST/include/n64.h" ]; then
            echo "Prebuilt libdragon detected; skipping install."
          else
            echo "Installing libdragon headers/libs..."
            rm -rf "$N64_INST"
            git clone --depth=1 https://github.com/DragonMinded/libdragon.git "$N64_INST"
            cd "$N64_INST"
            which mips64-elf-gcc
            make install
          fi

      # 5) Verify compiler availability
      - name: Verify compiler
        run: |
          set -e
          echo "PATH=$PATH"
          command -v mips64-elf-gcc
          mips64-elf-gcc --version | head -1

      # 6) Build ROM (Makefile in repo root)
      - name: Build ROM
        shell: bash
        run: |
          set -e
          echo "Building Shattered Realms ROM..."
          cd "$GITHUB_WORKSPACE"
          export PATH="$TOOLCHAIN_BIN:$PATH"
          export N64_INST="$N64_INST"
          echo "Repo listing (first 50 lines):"
          ls -R | head -50
          make clean all 2>&1 | tee build.log
          echo "Build complete."

      # 7) Upload artifacts
      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
