name: Build ROM (Cached Toolchain, correct path)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Restore cached toolchain + libdragon
      - name: Cache toolchain and libdragon
        uses: actions/cache@v4
        with:
          path: |
            /opt/libdragon/tools
            /opt/libdragon/include
            /opt/libdragon/lib
          key: n64-toolchain-libdragon

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Build toolchain (if not cached)
        run: |
          if [ ! -x /opt/libdragon/tools/build/bin/mips64-elf-gcc ]; then
            git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
            cd /opt/libdragon/tools
            export N64_INST=/opt/libdragon
            ./build-toolchain.sh
            cd /opt/libdragon
            export N64_INST=/opt/libdragon
            make install
          fi
          echo "/opt/libdragon/tools/build/bin" >> $GITHUB_PATH
          echo "/opt/libdragon/tools/mips64-elf/bin" >> $GITHUB_PATH
          echo "N64_INST=/opt/libdragon" >> $GITHUB_ENV
        shell: bash

      - name: Verify toolchain
        run: |
          which mips64-elf-gcc || echo "Not found"
          ls -R /opt/libdragon/tools | head -40
        shell: bash

      - name: Build ROM
        run: |
          export PATH=/opt/libdragon/tools/build/bin:/opt/libdragon/tools/mips64-elf/bin:$PATH
          export N64_INST=/opt/libdragon
          make clean all
        shell: bash

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs
