name: Build ROM (Finalized Cache + Toolchain Path Fix)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache toolchain and libdragon
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: |
            /opt/libdragon/tools
            /opt/libdragon/include
            /opt/libdragon/lib
          key: n64-toolchain-libdragon

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Build toolchain if missing
        run: |
          if [ ! -x /opt/libdragon/tools/toolchain/bin/mips64-elf-gcc ] && \
             [ ! -x /opt/libdragon/tools/build/bin/mips64-elf-gcc ] && \
             [ ! -x /opt/libdragon/tools/mips64-elf/bin/mips64-elf-gcc ]; then
            git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
            cd /opt/libdragon/tools
            export N64_INST=/opt/libdragon
            ./build-toolchain.sh
            cd /opt/libdragon
            export N64_INST=/opt/libdragon
            make install
          fi
          echo "/opt/libdragon/tools/toolchain/bin" >> $GITHUB_PATH
          echo "/opt/libdragon/tools/build/bin" >> $GITHUB_PATH
          echo "/opt/libdragon/tools/mips64-elf/bin" >> $GITHUB_PATH
          echo "N64_INST=/opt/libdragon" >> $GITHUB_ENV
        shell: bash

      - name: Save toolchain cache (always)
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            /opt/libdragon/tools
            /opt/libdragon/include
            /opt/libdragon/lib
          key: n64-toolchain-libdragon

      - name: Verify compiler location
        run: |
          echo "Checking for compiler binaries:"
          find /opt/libdragon/tools -type f -name "mips64-elf-gcc" || echo "Compiler not found!"
        shell: bash

      - name: Build ROM
        run: |
          export PATH=/opt/libdragon/tools/toolchain/bin:/opt/libdragon/tools/build/bin:/opt/libdragon/tools/mips64-elf/bin:$PATH
          export N64_INST=/opt/libdragon
          ln -sf $(which mips64-elf-gcc) /usr/local/bin/mips-n64-gcc || true
          ln -sf $(which mips64-elf-ld) /usr/local/bin/mips-n64-ld || true
          make clean all 2>&1 | tee build.log
        shell: bash

      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
