name: Build Shattered Realms ROM (prebuilt toolchain from release)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      N64_INST: /home/runner/.local/libdragon
      TOOLCHAIN_PATH: /home/runner/.local/libdragon/tools/toolchain/bin

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Download prebuilt toolchain from release
        run: |
          mkdir -p /home/runner/.local/libdragon/tools/toolchain
          cd /home/runner/.local/libdragon/tools/toolchain
          echo "Fetching prebuilt toolchain from release..."
          wget -q https://github.com/user-attachments/files/22749603/gcc-toolchain-mips64-latest.tar.gz
          tar -xzf gcc-toolchain-mips64-latest.tar.gz
          echo "/home/runner/.local/libdragon/tools/toolchain/bin" >> $GITHUB_PATH
          echo "N64_INST=/home/runner/.local/libdragon" >> $GITHUB_ENV

      - name: Prepare libdragon environment
        run: |
          # If directory exists, skip cloning entirely
          if [ -d /home/runner/.local/libdragon ]; then
            echo "libdragon directory already exists; skipping clone."
          else
            echo "libdragon not found; cloning repository..."
            git clone --depth=1 https://github.com/DragonMinded/libdragon.git /home/runner/.local/libdragon
          fi
          cd /home/runner/.local/libdragon
          export N64_INST=/home/runner/.local/libdragon
          export PATH="${TOOLCHAIN_PATH}:$PATH"
          make install

      - name: Verify compiler
        run: |
          echo "PATH=$PATH"
          command -v mips64-elf-gcc || (echo "Compiler still not found!" && exit 1)

      - name: Build ROM
        shell: bash
        run: |
          set -e
          echo "Building Shattered Realms ROM..."
          cd $GITHUB_WORKSPACE     # or cd $GITHUB_WORKSPACE/ZeldaShatteredRealms if your files are nested
          export PATH="/home/runner/.local/libdragon/tools/toolchain/bin:$PATH"
          export N64_INST=/home/runner/.local/libdragon
          which mips64-elf-gcc
          echo "Listing directory:"
          ls -R | head -50
          make clean all 2>&1 | tee build.log


      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
