name: Build ROM (Home-cached Libdragon)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      N64_INST: /home/runner/.local/libdragon
      TOOLCHAIN_PATH: /home/runner/.local/libdragon/tools/toolchain/bin

    steps:
      - uses: actions/checkout@v4

      - name: Cache toolchain & libdragon
        id: cache-libdragon
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.local/libdragon/tools
            /home/runner/.local/libdragon/include
            /home/runner/.local/libdragon/lib
          key: n64-homecache-v1-${{ runner.os }}

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Build toolchain if missing
        shell: bash
        run: |
          set -e
          if [ ! -x "${TOOLCHAIN_PATH}/mips64-elf-gcc" ]; then
            mkdir -p /home/runner/.local
            git clone --depth=1 https://github.com/DragonMinded/libdragon.git /home/runner/.local/libdragon
            cd /home/runner/.local/libdragon/tools
            export N64_INST=/home/runner/.local/libdragon
            ./build-toolchain.sh
            cd /home/runner/.local/libdragon
            make install
          fi
          echo "${TOOLCHAIN_PATH}" >> "$GITHUB_PATH"
          echo "N64_INST=/home/runner/.local/libdragon" >> "$GITHUB_ENV"

      - name: Save cache even if build fails
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.local/libdragon/tools
            /home/runner/.local/libdragon/include
            /home/runner/.local/libdragon/lib
          key: n64-homecache-v1-${{ runner.os }}

      - name: Verify compiler
        shell: bash
        run: |
          echo "PATH=$PATH"
          find /home/runner/.local/libdragon/tools -maxdepth 4 -type f -name "mips64-elf-gcc"

      - name: Build ROM
        shell: bash
        run: |
          set -e
          export PATH="${TOOLCHAIN_PATH}:$PATH"
          export N64_INST=/home/runner/.local/libdragon
          command -v mips64-elf-gcc
          make clean all 2>&1 | tee build.log

      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
