name: Build ROM (Toolchain from source, fixed path)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Build toolchain from source
        run: |
          git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
          cd /opt/libdragon/tools
          ./build-toolchain.sh
          echo "/opt/libdragon/tools/mips64-elf/bin" >> $GITHUB_PATH
          echo "N64_INST=/opt/libdragon" >> $GITHUB_ENV

      - name: Install libdragon
        run: |
          cd /opt/libdragon
          make install

      - name: Build ROM
        run: |
          make clean all

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs
