name: Build Shattered Realms ROM (official toolchain .deb)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      # The .deb installs here and sets up headers/libs/tools
      N64_INST: /opt/libdragon

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex dpkg

      # Install the official prebuilt toolchain (.deb)
      - name: Install libdragon toolchain (.deb)
        run: |
          set -e
          cd /tmp
          echo "Fetching official libdragon toolchain (.deb)..."
          wget -q https://github.com/DragonMinded/libdragon/releases/download/toolchain-continuous-prerelease/gcc-toolchain-mips64-x86_64.deb
          sudo dpkg -i gcc-toolchain-mips64-x86_64.deb
          echo "N64_INST=/opt/libdragon" >> "$GITHUB_ENV"
          echo "/opt/libdragon/bin" >> "$GITHUB_PATH"

      # Build & install libdragon headers/libs/tools if not already present
      - name: Build & install libdragon (headers/libs/tools)
        run: |
          set -e
          export N64_INST=/opt/libdragon
          export PATH=/opt/libdragon/bin:$PATH
          if [ -f "/opt/libdragon/mips64-elf/include/libdragon.h" ]; then
            echo "libdragon headers present."
          else
            echo "Cloning and installing libdragon..."
            git clone --depth=1 https://github.com/DragonMinded/libdragon.git /tmp/libdragon-src
            cd /tmp/libdragon-src
            which mips64-elf-gcc
            ./build.sh   # installs to $N64_INST
          fi

      # Ensure ROM header exists (some package layouts omit it). If missing, copy from libdragon repo.
      - name: Ensure N64 ROM header exists
        run: |
          set -e
          export N64_INST=/opt/libdragon
          # Try common locations
          if [ -f "/opt/libdragon/lib/header" ] || [ -f "/opt/libdragon/mips64-elf/lib/header" ]; then
            echo "Header already present."
            exit 0
          fi
          echo "Header missing; fetching from libdragon repo..."
          rm -rf /tmp/libdragon-header
          git clone --depth=1 https://github.com/DragonMinded/libdragon.git /tmp/libdragon-header
          # Standard location under the repo:
          if [ -f /tmp/libdragon-header/tools/n64tool/header ]; then
            sudo mkdir -p /opt/libdragon/lib
            sudo cp /tmp/libdragon-header/tools/n64tool/header /opt/libdragon/lib/header
            echo "Installed header to /opt/libdragon/lib/header"
          else
            echo "ERROR: Could not locate header in libdragon repo." >&2
            exit 1
          fi

      - name: Verify toolchain & tools
        run: |
          set -e
          export PATH=/opt/libdragon/bin:$PATH
          command -v mips64-elf-gcc
          mips64-elf-gcc --version | head -1
          command -v n64tool
          command -v mkdfs
          ls -l /opt/libdragon/lib || true
          ls -l /opt/libdragon/mips64-elf/lib || true

      - name: Build ROM
        shell: bash
        run: |
          set -e
          export N64_INST=/opt/libdragon
          export PATH=/opt/libdragon/bin:$PATH
          echo "Repo listing (first 50 lines):"
          ls -R | head -50
          make clean all 2>&1 | tee build.log
          echo "Build complete."

      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
