name: Build ROM (No-Docker, verified)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Build and activate libdragon toolchain
        run: |
          git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
          cd /opt/libdragon
          ./build-toolchain.sh
          echo "export PATH=/opt/libdragon/tools/mips64-elf/bin:$PATH" >> $HOME/.bashrc
          echo "PATH=/opt/libdragon/tools/mips64-elf/bin:$PATH" >> $GITHUB_ENV
        shell: bash

      - name: Verify compiler
        run: |
          echo "PATH=$PATH"
          which mips-n64-gcc || true
          ls /opt/libdragon/tools/mips64-elf/bin || true
        shell: bash

      - name: Build ROM
        run: |
          export PATH=/opt/libdragon/tools/mips64-elf/bin:$PATH
          make clean all
        shell: bash

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs
