name: Build ROM (libdragon-dev)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Use the full SDK image that includes libdragon headers, libs, n64.ld, and tools
    container:
      image: ghcr.io/dragonminded/libdragon-dev:latest
      options: --user root
    env:
      # Keep a sane PATH and include both common tool locations
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/libdragon/bin:/n64_toolchain/bin
      N64_INST: /opt/libdragon

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Diagnose SDK and tools (non-fatal)
        shell: sh
        run: |
          echo "Probing tools (non-fatal if some are missing):"
          command -v mips64-elf-gcc || true
          command -v n64tool || true
          command -v mkdfs || true
          command -v chksum64 || true
          echo "Probing headers/libs:"
          [ -f /opt/libdragon/mips64-elf/include/libdragon.h ] && echo "libdragon.h OK" || echo "libdragon.h MISSING"
          [ -f /opt/libdragon/mips64-elf/lib/n64.ld ] && echo "n64.ld OK" || echo "n64.ld MISSING"
          ls -l /opt/libdragon/mips64-elf/lib 2>/dev/null || true
          echo "PATH=$PATH"
          echo "N64_INST=$N64_INST"

      - name: Build
        shell: sh
        run: |
          set -e
          echo "Repo structure:"
          ls -R | head -50 || true
          make clean all 2>&1 | tee build.log
          echo "✅ Build complete."
          echo "Built files:"
          ls -l shattered_realms.* romfs.dfs || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
            build.log
          if-no-files-found: error
