name: n64-build
on:
  push:
  pull_request:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest

    # 💡 Run ALL steps inside the official libdragon toolchain container
    container:
      image: ghcr.io/dragonminded/libdragon:latest

    defaults:
      run:
        shell: bash

    env:
      N64_INST: /opt/libdragon
      PATH: /opt/libdragon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Mark workspace as safe for Git
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      # (Optional) parse your MF/BL/MC revs from commit subject, default 000
      - name: Parse rev tokens
        id: revs
        run: |
          set -e
          MSG="$(git log -1 --pretty=%B | tr '\n' ' ')"
          MF=$(grep -oE 'MF[0-9]{3}' <<<"$MSG" | tail -n1 | sed 's/MF//') || true
          BL=$(grep -oE 'BL[0-9]{3}' <<<"$MSG" | tail -n1 | sed 's/BL//') || true
          MC=$(grep -oE 'MC[0-9]{3}' <<<"$MSG" | tail -n1 | sed 's/MC//') || true
          echo "MFREV=${MF:-000}" >> $GITHUB_OUTPUT
          echo "BLREV=${BL:-000}" >> $GITHUB_OUTPUT
          echo "MCREV=${MC:-000}" >> $GITHUB_OUTPUT
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Toolchain sanity (non-fatal)
        continue-on-error: true
        run: |
          echo "mips64-elf-gcc: $(command -v mips64-elf-gcc || echo MISSING)"
          mips64-elf-gcc --version | head -n1 || true
          echo "n64tool: $(command -v n64tool || echo MISSING)"
          echo "n64elfcompress: $(command -v n64elfcompress || echo MISSING)"
          ls -ld /opt/libdragon /opt/libdragon/bin || true

      - name: Build (always logs; stamps ROM title)
        run: |
          set -e
          TITLE="SR MF${{ steps.revs.outputs.MFREV }} MC${{ steps.revs.outputs.MCREV }}"
          echo "Using ROM TITLE: $TITLE"
          ( make clean all TITLE="$TITLE" ) 2>&1 | tee build.log || true
          echo "Built files after make:"
          ls -l shattered_realms.* romfs.dfs || true
          if [ -f shattered_realms.z64 ]; then
            echo "ROM header (16 bytes):"
            xxd -l 16 -g 1 shattered_realms.z64 || true
          fi

      - name: Upload artifacts (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: n64-build-output-MF${{ steps.revs.outputs.MFREV }}-BL${{ steps.revs.outputs.BLREV }}-MC${{ steps.revs.outputs.MCREV }}-${{ steps.revs.outputs.SHORT_SHA }}
          path: |
            build.log
            shattered_realms.z64
            shattered_realms.elf
            shattered_realms.bin
            romfs.dfs
          if-no-files-found: warn
