name: Build ROM (No-Docker)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Build libdragon toolchain
        run: |
          git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
          cd /opt/libdragon
          ./build-toolchain.sh
        shell: bash

      - name: Add toolchain to PATH
        run: echo "/opt/libdragon/tools/mips64-elf/bin" >> $GITHUB_PATH

      - name: Verify toolchain
        run: |
          which mips-n64-gcc || echo "Toolchain not found!"
          mips-n64-gcc -v

      - name: Build ROM
        run: make clean all

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs
