name: Build ROM (Prebuilt Toolchain)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install prebuilt N64 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y wget tar
          wget https://github.com/n64-tools/gcc-toolchain-mips64/releases/download/v1.0.0/mips64-elf-toolchain-linux.tar.gz
          tar -xzf mips64-elf-toolchain-linux.tar.gz
          sudo mv gcc-toolchain-mips64 /opt/mips64-elf-toolchain
          echo "/opt/mips64-elf-toolchain/bin" >> $GITHUB_PATH
          which mips-n64-gcc || echo "Toolchain not found after download"

      - name: Build libdragon runtime
        run: |
          git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
          cd /opt/libdragon
          export PATH=/opt/mips64-elf-toolchain/bin:$PATH
          make -C libdragon install
        shell: bash

      - name: Build ROM
        run: |
          export PATH=/opt/mips64-elf-toolchain/bin:$PATH
          make clean all
        shell: bash

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs
