name: Build ROM (libdragon container)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/dragonminded/libdragon:latest
    env:
      N64_INST: /opt/libdragon
      PATH: /opt/libdragon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Tool sanity (SDK + tools must already be in the image)
        shell: sh
        run: |
          set -e
          command -v mips64-elf-gcc
          command -v n64tool
          command -v mkdfs
          command -v n64elfcompress
          ls -l /opt/libdragon/mips64-elf/lib/n64.ld
          ls -l /opt/libdragon/mips64-elf/include/libdragon.h

      - name: Build
        shell: sh
        run: |
          set -e
          make clean all 2>&1 | tee build.log
          echo "Built files:"
          ls -l shattered_realms.* romfs.dfs || true
          if [ -f shattered_realms.z64 ]; then
            echo "ROM header (16 bytes):"
            xxd -l 16 -g 1 shattered_realms.z64 || true
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
            build.log
          if-no-files-found: error
