name: Build ROM

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prep toolchain path
        run: |
          echo "N64_INST=/opt/libdragon" >> $GITHUB_ENV
          echo "/opt/libdragon/bin" >> $GITHUB_PATH

      - name: Install build deps
        run: sudo apt-get update && sudo apt-get install -y build-essential curl gcc

      - name: Ensure checksum tool
        run: |
          sudo mkdir -p /opt/libdragon/bin
          # Build chksum64 if missing
          if [ ! -x /opt/libdragon/bin/chksum64 ]; then
            curl -sL https://raw.githubusercontent.com/DragonMinded/libdragon/trunk/tools/chksum64.c -o /tmp/chksum64.c
            gcc -O2 /tmp/chksum64.c -o /opt/libdragon/bin/chksum64
          fi

      - name: Build
        run: |
          set -e
          make clean all
          echo "Build complete."

      - name: Upload ROM artifact
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
          if-no-files-found: error
