name: Build Toolchain and ROM

on:
  workflow_dispatch:

jobs:
  build-toolchain:
    runs-on: ubuntu-latest
    outputs:
      toolchain-path: ${{ steps.upload.outputs.artifact-path }}
    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex
      - name: Build toolchain
        run: |
          mkdir -p /home/runner/.local/libdragon
          git clone --depth=1 https://github.com/DragonMinded/libdragon.git /home/runner/.local/libdragon
          cd /home/runner/.local/libdragon/tools
          export N64_INST=/home/runner/.local/libdragon
          ./build-toolchain.sh
          cd /home/runner/.local/libdragon
          make install
          cd /home/runner/.local/libdragon/tools
          tar -czf $GITHUB_WORKSPACE/mips64-elf-toolchain-cache.tar.gz .
      - id: upload
        uses: actions/upload-artifact@v4
        with:
          name: n64-toolchain-cache
          path: mips64-elf-toolchain-cache.tar.gz

  build-rom:
    needs: build-toolchain
    runs-on: ubuntu-latest
    env:
      N64_INST: /home/runner/.local/libdragon
      TOOLCHAIN_PATH: /home/runner/.local/libdragon/tools/toolchain/bin
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: n64-toolchain-cache
          path: /home/runner/.local/libdragon/tools
      - run: |
          cd /home/runner/.local/libdragon/tools
          tar -xzf mips64-elf-toolchain-cache.tar.gz
          echo "${TOOLCHAIN_PATH}" >> "$GITHUB_PATH"
          echo "N64_INST=/home/runner/.local/libdragon" >> "$GITHUB_ENV"
      - run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex
      - run: |
          export PATH="${TOOLCHAIN_PATH}:$PATH"
          export N64_INST=/home/runner/.local/libdragon
          make clean all 2>&1 | tee build.log
      - uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs
      - uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
