name: Build ROM (libdragon container)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Use the official libdragon image so the toolchain is present
    container:
      image: ghcr.io/dragonminded/libdragon:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Verify toolchain in container
        run: |
          set -e
          which mips64-elf-gcc
          which n64tool
          which mkdfs
          which chksum64
          echo "N64_INST=${N64_INST:-/opt/libdragon}"
          ls -l /opt/libdragon/bin

      - name: Build
        env:
          N64_INST: /opt/libdragon
          PATH: /opt/libdragon/bin:${PATH}
        run: |
          set -e
          echo "Repo structure:"
          ls -R | head -50
          make clean all 2>&1 | tee build.log
          echo "✅ Build complete."
          echo "Built files:"
          ls -l shattered_realms.* romfs.dfs || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
            build.log
          if-no-files-found: error
