name: Build ROM (libdragon + IPL3 verified)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --user root
    env:
      N64_INST: /opt/libdragon
      PATH: /opt/libdragon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git python3 pkg-config libpng-dev zlib1g-dev curl jq xxd

      - name: Install libdragon SDK (header + tools)
        run: |
          set -e
          git clone --depth=1 https://github.com/DragonMinded/libdragon.git /tmp/libdragon
          cd /tmp/libdragon
          ./build.sh
          cp -r /tmp/libdragon/* /opt/libdragon/
          echo "Installed libdragon. Checking header:"
          ls -l /opt/libdragon/lib/header || (echo "❌ Missing IPL3 header" && exit 1)

      - name: Diagnose toolchain
        run: |
          echo "Toolchain tools:"
          command -v mips64-elf-gcc
          command -v n64tool
          command -v mkdfs
          command -v chksum64
          ls -l /opt/libdragon/lib/header || true
          echo "SDK lib contents:"
          ls -l /opt/libdragon/lib || true

      - name: Build
        run: |
          set -e
          echo "--- Makefile paths ---"
          make showpaths
          echo "----------------------"
          make clean all 2>&1 | tee build.log
          echo "✅ Build complete."
          ls -l shattered_realms.* romfs.dfs || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
            build.log
          if-no-files-found: error
