name: Build ROM (libdragon container)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # Pin to a known-good libdragon image that includes n64tool/mkdfs/chksum64 and libs
    container:
      image: ghcr.io/dragonminded/libdragon:latest
      options: --user root

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show toolchain (non-fatal diagnostics)
        shell: bash
        run: |
          set +e
          echo "Probing tools (non-fatal if missing):"
          which mips64-elf-gcc || true
          which n64tool || true
          which mkdfs || true
          which chksum64 || true
          echo "Listing /opt/libdragon/bin:"
          ls -l /opt/libdragon/bin || true
          echo "Env:"
          echo "N64_INST=${N64_INST:-/opt/libdragon}"

      - name: Build
        shell: bash
        env:
          N64_INST: /opt/libdragon
          PATH: /opt/libdragon/bin:${PATH}
        run: |
          set -e
          echo "Repo structure:"
          ls -R | head -50
          make clean all 2>&1 | tee build.log
          echo "✅ Build complete."
          echo "Built files:"
          ls -l shattered_realms.* romfs.dfs || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
            build.log
          if-no-files-found: error
