name: Build ROM (Cached Toolchain + Debug)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Restore any existing cached toolchain/libdragon
      - name: Cache toolchain and libdragon
        id: cache-toolchain
        uses: actions/cache@v4
        with:
          path: |
            /opt/libdragon/tools
            /opt/libdragon/include
            /opt/libdragon/lib
          key: n64-toolchain-libdragon

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Build toolchain if missing
        run: |
          if [ ! -x /opt/libdragon/tools/build/bin/mips64-elf-gcc ] && [ ! -x /opt/libdragon/tools/mips64-elf/bin/mips64-elf-gcc ]; then
            git clone https://github.com/DragonMinded/libdragon.git /opt/libdragon
            cd /opt/libdragon/tools
            export N64_INST=/opt/libdragon
            ./build-toolchain.sh
            cd /opt/libdragon
            export N64_INST=/opt/libdragon
            make install
          fi
          echo "/opt/libdragon/tools/build/bin" >> $GITHUB_PATH
          echo "/opt/libdragon/tools/mips64-elf/bin" >> $GITHUB_PATH
          echo "N64_INST=/opt/libdragon" >> $GITHUB_ENV
        shell: bash

      # Force a cache save even if later steps fail
      - name: Save toolchain cache
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            /opt/libdragon/tools
            /opt/libdragon/include
            /opt/libdragon/lib
          key: n64-toolchain-libdragon

      - name: Verify toolchain
        run: |
          echo "Checking compiler..."
          if [ -x /opt/libdragon/tools/build/bin/mips64-elf-gcc ]; then
            echo "Found compiler in build/bin:"
            ls -l /opt/libdragon/tools/build/bin/mips64-elf-gcc
          elif [ -x /opt/libdragon/tools/mips64-elf/bin/mips64-elf-gcc ]; then
            echo "Found compiler in mips64-elf/bin:"
            ls -l /opt/libdragon/tools/mips64-elf/bin/mips64-elf-gcc
          else
            echo "Compiler not found!"
          fi
        shell: bash

      - name: Build ROM
        run: |
          export PATH=/opt/libdragon/tools/build/bin:/opt/libdragon/tools/mips64-elf/bin:$PATH
          export N64_INST=/opt/libdragon
          make clean all 2>&1 | tee build.log
        shell: bash

      # Upload final ROM if it exists
      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      # Upload intermediate objects/logs for debugging
      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
