name: Build ZeldaSR ROM + hello example

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      N64_INST: /opt/libdragon
      PATH: /opt/libdragon/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          set -e
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git python3 pkg-config libpng-dev zlib1g-dev \
            jq curl xxd

      - name: Install mips64-elf toolchain (arch-aware)
        run: |
          set -e
          ARCH="$(dpkg --print-architecture)"
          API="https://api.github.com/repos/DragonMinded/libdragon/releases/tags/toolchain-continuous-prerelease"
          ASSETS_JSON="$(curl -fsSL "$API")"
          case "$ARCH" in
            amd64) PATTERN='(x86_64|amd64)\.deb$' ;;
            arm64) PATTERN='(aarch64|arm64)\.deb$' ;;
            *) echo "Unsupported arch: $ARCH"; echo "$ASSETS_JSON" | jq -r '.assets[].name'; exit 1 ;;
          esac
          DEB_URL="$(echo "$ASSETS_JSON" | jq -r --arg re "$PATTERN" '.assets[] | select(.name | test($re)) | .browser_download_url' | head -n1)"
          [ -n "$DEB_URL" ] || { echo "No toolchain .deb matched $PATTERN"; exit 1; }
          echo "Downloading toolchain: $DEB_URL"
          curl -fsSL "$DEB_URL" -o /tmp/n64-toolchain.deb
          sudo dpkg -i /tmp/n64-toolchain.deb || true
          command -v mips64-elf-gcc || { echo "mips64-elf-gcc not in PATH"; exit 1; }
          echo "Toolchain OK at $(command -v mips64-elf-gcc)"

      - name: Build & install libdragon (headers, libs, tools)
        run: |
          set -e
          git clone --depth=1 https://github.com/DragonMinded/libdragon.git /tmp/libdragon
          pushd /tmp/libdragon
          ./build.sh
          popd
          command -v n64tool || { echo "n64tool missing after build.sh"; exit 1; }
          command -v mkdfs   || { echo "mkdfs missing after build.sh"; exit 1; }

      - name: Build ZeldaSR
        run: |
          set -e
          echo "--- Makefile paths ---"
          make showpaths
          echo "----------------------"
          make clean all 2>&1 | tee build.log
          echo "ZeldaSR ROM header (16 bytes):"
          xxd -l 16 -g 1 shattered_realms.z64
          echo "ZeldaSR ROM size (bytes):"
          wc -c < shattered_realms.z64

      - name: Build libdragon hello example
        run: |
          set -e
          pushd /tmp/libdragon/examples/hello
          make clean && make
          popd
          cp /tmp/libdragon/examples/hello/hello.z64 hello_example.z64
          echo "hello_example ROM header (16 bytes):"
          xxd -l 16 -g 1 hello_example.z64
          echo "hello_example ROM size (bytes):"
          wc -c < hello_example.z64

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zeldasr_and_example
          path: |
            shattered_realms.z64
            shattered_realms.elf
            romfs.dfs
            build.log
            hello_example.z64
          if-no-files-found: error
