name: Build ROM (Prebuilt Toolchain + Cache)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      N64_INST: /home/runner/.local/libdragon
      TOOLCHAIN_PATH: /home/runner/.local/libdragon/tools/toolchain/bin

    steps:
      - uses: actions/checkout@v4

      # Restore cached toolchain/libdragon if present
      - name: Cache toolchain and libdragon
        id: cache-libdragon
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.local/libdragon/tools
            /home/runner/.local/libdragon/include
            /home/runner/.local/libdragon/lib
          key: n64-prebuilt-v1-${{ runner.os }}

      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git wget python3 unzip texinfo bison flex

      - name: Download pre-built toolchain
        run: |
          mkdir -p /home/runner/.local/libdragon/tools/toolchain
          cd /home/runner/.local/libdragon/tools/toolchain
          echo "Fetching pre-built toolchain..."
          wget -q https://github.com/DragonMinded/libdragon/releases/download/toolchain-latest/mips64-elf-toolchain-linux.tar.gz
          tar -xzf mips64-elf-toolchain-linux.tar.gz
          echo "${TOOLCHAIN_PATH}" >> "$GITHUB_PATH"
          echo "N64_INST=/home/runner/.local/libdragon" >> "$GITHUB_ENV"

      - name: Build libdragon libraries (lightweight)
        shell: bash
        run: |
          set -e
          if [ ! -d /home/runner/.local/libdragon/lib ]; then
            git clone --depth=1 https://github.com/DragonMinded/libdragon.git /home/runner/.local/libdragon
            cd /home/runner/.local/libdragon
            export N64_INST=/home/runner/.local/libdragon
            export PATH="${TOOLCHAIN_PATH}:$PATH"
            make install
          fi

      # Save cache even if ROM fails to build
      - name: Save cache (always)
        if: always()
        uses: actions/cache@v4
        with:
          path: |
            /home/runner/.local/libdragon/tools
            /home/runner/.local/libdragon/include
            /home/runner/.local/libdragon/lib
          key: n64-prebuilt-v1-${{ runner.os }}

      - name: Verify compiler
        shell: bash
        run: |
          echo "PATH=$PATH"
          command -v mips64-elf-gcc || (echo "Compiler still not found!" && exit 1)

      - name: Build ROM
        shell: bash
        run: |
          set -e
          export PATH="${TOOLCHAIN_PATH}:$PATH"
          export N64_INST=/home/runner/.local/libdragon
          make clean all 2>&1 | tee build.log

      - name: Upload ROM artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-rom
          path: |
            *.z64
            romfs.dfs

      - name: Upload Debug Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: shattered_realms-debug
          path: |
            src/*.o
            *.elf
            Makefile
            build.log
